// <auto-generated />
using System;
using Console_Care.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Console_Care.Migrations
{
    [DbContext(typeof(Appdbcontext))]
    [Migration("20241212104654_empl")]
    partial class empl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Console_Care.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Order")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ps4OrPs5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateOfOrder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfCustomer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("customer");
                });

            modelBuilder.Entity("Console_Care.Models.Employee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("Console_Care.Models.FollowUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FaultStatement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdOfCustomer")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastFollowUpDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MaintenanceImplementationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NextFollowUpDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuggestionsAndIssues")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdOfCustomer")
                        .IsUnique();

                    b.ToTable("followUp");
                });

            modelBuilder.Entity("Console_Care.Models.Materials", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Storage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("materials");
                });

            modelBuilder.Entity("Console_Care.Models.moderator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdvertiseDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConvertToEmployee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaultStatement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOfAssistant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOfDataEntry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOfTechnician")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotesToMaintenanceTeam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RemainingTeam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouteDistributionOfficer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sequence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusOfOrder")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisitClassification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VisitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VisitStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("moderator");
                });

            modelBuilder.Entity("Customermoderator", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("moderatorId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId", "moderatorId");

                    b.HasIndex("moderatorId");

                    b.ToTable("Customermoderator");
                });

            modelBuilder.Entity("EmployeeMaterials", b =>
                {
                    b.Property<int>("Employeesid")
                        .HasColumnType("int");

                    b.Property<int>("materialsId")
                        .HasColumnType("int");

                    b.HasKey("Employeesid", "materialsId");

                    b.HasIndex("materialsId");

                    b.ToTable("EmployeeMaterials");
                });

            modelBuilder.Entity("Console_Care.Models.FollowUp", b =>
                {
                    b.HasOne("Console_Care.Models.Customer", "Customer")
                        .WithOne("followUp")
                        .HasForeignKey("Console_Care.Models.FollowUp", "IdOfCustomer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Customermoderator", b =>
                {
                    b.HasOne("Console_Care.Models.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Console_Care.Models.moderator", null)
                        .WithMany()
                        .HasForeignKey("moderatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EmployeeMaterials", b =>
                {
                    b.HasOne("Console_Care.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("Employeesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Console_Care.Models.Materials", null)
                        .WithMany()
                        .HasForeignKey("materialsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Console_Care.Models.Customer", b =>
                {
                    b.Navigation("followUp")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
