// <auto-generated />
using System;
using Console_Care.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Console_Care.Migrations
{
    [DbContext(typeof(Appdbcontext))]
    [Migration("20250129113329_nameofcust")]
    partial class nameofcust
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Console_Care.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotesToMaintenanceTeam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouteDistributionOfficer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisitStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Console_Care.Models.AdminCustomers", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId", "AdminId");

                    b.HasIndex("AdminId");

                    b.ToTable("AdminCustomers");
                });

            modelBuilder.Entity("Console_Care.Models.AdminEmployee", b =>
                {
                    b.Property<int>("Employeeid")
                        .HasColumnType("int");

                    b.Property<int>("adminId")
                        .HasColumnType("int");

                    b.HasKey("Employeeid", "adminId");

                    b.HasIndex("adminId");

                    b.ToTable("AdminEmployee");
                });

            modelBuilder.Entity("Console_Care.Models.AdminItinerary", b =>
                {
                    b.Property<int>("itinerarieId")
                        .HasColumnType("int");

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<int>("ItineraryId")
                        .HasColumnType("int");

                    b.HasKey("itinerarieId", "AdminId");

                    b.HasIndex("AdminId");

                    b.HasIndex("ItineraryId");

                    b.ToTable("AdminItinerary");
                });

            modelBuilder.Entity("Console_Care.Models.BuyingMaterials", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameOfBuyer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOfMaterials")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoPiece")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceofPiece")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.ToTable("BuyingMaterials");
                });

            modelBuilder.Entity("Console_Care.Models.Cash", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoOfProcess")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoOfaccount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Outgoing")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("paid")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Cash");
                });

            modelBuilder.Entity("Console_Care.Models.Closeday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Cash")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Expenses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Origins")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PaidPurchases")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PaidSales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Procurement")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Remainingpurchases")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Remainingsales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Sales")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Closeday");
                });

            modelBuilder.Entity("Console_Care.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Invoiceid")
                        .HasColumnType("int");

                    b.Property<int?>("ItineraryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Order")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ps4OrPs5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateOfOrder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfCustomer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Invoiceid")
                        .IsUnique()
                        .HasFilter("[Invoiceid] IS NOT NULL");

                    b.HasIndex("ItineraryId");

                    b.ToTable("customer");
                });

            modelBuilder.Entity("Console_Care.Models.CustomerDataBases", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ps4OrPs5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfCustomer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("CustomerDataBases");
                });

            modelBuilder.Entity("Console_Care.Models.CustomerDataBasesInvoice", b =>
                {
                    b.Property<string>("CustomerDataBasesid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Invoicesid")
                        .HasColumnType("int");

                    b.HasKey("CustomerDataBasesid", "Invoicesid");

                    b.HasIndex("Invoicesid");

                    b.ToTable("CustomerDataBasessInvoice");
                });

            modelBuilder.Entity("Console_Care.Models.Employee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("Console_Care.Models.EmployeeItinerary", b =>
                {
                    b.Property<int>("ItineraryId")
                        .HasColumnType("int");

                    b.Property<int>("Employeeid")
                        .HasColumnType("int");

                    b.HasKey("ItineraryId", "Employeeid");

                    b.HasIndex("Employeeid");

                    b.ToTable("EmployeeItinerary");
                });

            modelBuilder.Entity("Console_Care.Models.EmployeeMaterials", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Employeesid")
                        .HasColumnType("int");

                    b.Property<int>("Quantities")
                        .HasColumnType("int");

                    b.Property<int?>("QuantityUsed")
                        .HasColumnType("int");

                    b.Property<int>("materialsId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Employeesid");

                    b.HasIndex("materialsId");

                    b.ToTable("EmployeeMaterials");
                });

            modelBuilder.Entity("Console_Care.Models.Invoice", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("datetime2");

                    b.PrimitiveCollection<string>("Discount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Discountwarranty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Paid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total_Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total_Amountafterdisc")
                        .HasColumnType("decimal(18,2)");

                    b.PrimitiveCollection<string>("TotalpriceForitem")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("item")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nameofcustomer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nameoftechnecal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("number")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("price")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("quantity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("remaining")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("specialDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("typeofinvoice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Console_Care.Models.Itinerary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FaultStatement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOfAssistant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nameoftech")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RemainingTeam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusOfOrder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisitClassification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("itineraries");
                });

            modelBuilder.Entity("Console_Care.Models.Materials", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Storage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("minQuantity")
                        .HasColumnType("int");

                    b.Property<int>("priceForHome")
                        .HasColumnType("int");

                    b.Property<int>("priceForPs")
                        .HasColumnType("int");

                    b.Property<int>("priceForbuy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("materials");
                });

            modelBuilder.Entity("Console_Care.Models.Other_expenses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisbursementName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ExpenseValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Other_expenses");
                });

            modelBuilder.Entity("Console_Care.Models.Purchase_Payments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("InvoiceValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Invoicenumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PaidValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("remaining")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Purchase_Payments");
                });

            modelBuilder.Entity("Console_Care.Models.StaticAssets", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Specifications")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("typeOfStaticAssets")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StaticAssets");
                });

            modelBuilder.Entity("Console_Care.Models.followUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FaultStatement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdOfCustomer")
                        .HasColumnType("int");

                    b.Property<int?>("IdOfEmployee")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastFollowUpDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Maintenance_Implementation_Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NextFollowUpDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SuggestionsAndIssues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfCustomer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("WarrantyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("stateOfFolowUp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdOfCustomer")
                        .IsUnique();

                    b.HasIndex("IdOfEmployee");

                    b.ToTable("followUp");
                });

            modelBuilder.Entity("Console_Care.Models.sales", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("Interesting")
                        .HasColumnType("bit");

                    b.Property<string>("NameOfCustomer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nameofdataentry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeOfCall")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("sales");
                });

            modelBuilder.Entity("Console_Care.Models.static_expenses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("April")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("August")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("December")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Employee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("February")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("January")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("July")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("June")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("March")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("May")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NameOfDepartment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("November")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("October")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("September")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Target")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("static_expenses");
                });

            modelBuilder.Entity("Console_Care.identity.Appuser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Console_Care.Models.AdminCustomers", b =>
                {
                    b.HasOne("Console_Care.Models.Admin", "Admin")
                        .WithMany("AdminCustomers")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Console_Care.Models.Customer", "Customer")
                        .WithMany("AdminCustomers")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Console_Care.Models.AdminEmployee", b =>
                {
                    b.HasOne("Console_Care.Models.Employee", "Employee")
                        .WithMany("AdminEmployees")
                        .HasForeignKey("Employeeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Console_Care.Models.Admin", "Admin")
                        .WithMany("adminEmployee")
                        .HasForeignKey("adminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Console_Care.Models.AdminItinerary", b =>
                {
                    b.HasOne("Console_Care.Models.Admin", "Admin")
                        .WithMany("AdminItineraries")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Console_Care.Models.Itinerary", "Itinerary")
                        .WithMany("AdminItineraries")
                        .HasForeignKey("ItineraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Itinerary");
                });

            modelBuilder.Entity("Console_Care.Models.Customer", b =>
                {
                    b.HasOne("Console_Care.Models.Invoice", "Invoice")
                        .WithOne("Customer")
                        .HasForeignKey("Console_Care.Models.Customer", "Invoiceid");

                    b.HasOne("Console_Care.Models.Itinerary", "Itinerary")
                        .WithMany("Customer")
                        .HasForeignKey("ItineraryId");

                    b.Navigation("Invoice");

                    b.Navigation("Itinerary");
                });

            modelBuilder.Entity("Console_Care.Models.CustomerDataBasesInvoice", b =>
                {
                    b.HasOne("Console_Care.Models.CustomerDataBases", "CustomerDataBases")
                        .WithMany("CustomerDataBasesInvoice")
                        .HasForeignKey("CustomerDataBasesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Console_Care.Models.Invoice", "Invoice")
                        .WithMany("CustomerDataBasesInvoice")
                        .HasForeignKey("Invoicesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerDataBases");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Console_Care.Models.EmployeeItinerary", b =>
                {
                    b.HasOne("Console_Care.Models.Employee", "Employee")
                        .WithMany("employeeItineraries")
                        .HasForeignKey("Employeeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Console_Care.Models.Itinerary", "Itinerary")
                        .WithMany("employeeItineraries")
                        .HasForeignKey("ItineraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Itinerary");
                });

            modelBuilder.Entity("Console_Care.Models.EmployeeMaterials", b =>
                {
                    b.HasOne("Console_Care.Models.Employee", "Employee")
                        .WithMany("materials")
                        .HasForeignKey("Employeesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Console_Care.Models.Materials", "Materials")
                        .WithMany("employeeMaterialsmaterials")
                        .HasForeignKey("materialsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Materials");
                });

            modelBuilder.Entity("Console_Care.Models.followUp", b =>
                {
                    b.HasOne("Console_Care.Models.Customer", "Customer")
                        .WithOne("followUp")
                        .HasForeignKey("Console_Care.Models.followUp", "IdOfCustomer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Console_Care.Models.Employee", "Employee")
                        .WithMany("followups")
                        .HasForeignKey("IdOfEmployee");

                    b.Navigation("Customer");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Console_Care.identity.Appuser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Console_Care.identity.Appuser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Console_Care.identity.Appuser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Console_Care.identity.Appuser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Console_Care.Models.Admin", b =>
                {
                    b.Navigation("AdminCustomers");

                    b.Navigation("AdminItineraries");

                    b.Navigation("adminEmployee");
                });

            modelBuilder.Entity("Console_Care.Models.Customer", b =>
                {
                    b.Navigation("AdminCustomers");

                    b.Navigation("followUp")
                        .IsRequired();
                });

            modelBuilder.Entity("Console_Care.Models.CustomerDataBases", b =>
                {
                    b.Navigation("CustomerDataBasesInvoice");
                });

            modelBuilder.Entity("Console_Care.Models.Employee", b =>
                {
                    b.Navigation("AdminEmployees");

                    b.Navigation("employeeItineraries");

                    b.Navigation("followups");

                    b.Navigation("materials");
                });

            modelBuilder.Entity("Console_Care.Models.Invoice", b =>
                {
                    b.Navigation("Customer");

                    b.Navigation("CustomerDataBasesInvoice");
                });

            modelBuilder.Entity("Console_Care.Models.Itinerary", b =>
                {
                    b.Navigation("AdminItineraries");

                    b.Navigation("Customer");

                    b.Navigation("employeeItineraries");
                });

            modelBuilder.Entity("Console_Care.Models.Materials", b =>
                {
                    b.Navigation("employeeMaterialsmaterials");
                });
#pragma warning restore 612, 618
        }
    }
}
